version: '3'
services:
  rest_api:
    build:
      context: .
      dockerfile: Dockerfile_Backend
    image: &backend backend
    restart: "no"
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    env_file: &envfile
      - env.env
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/backend
    depends_on:
      - broker

  worker:
    build:
      context: .
      dockerfile: Dockerfile_Backend
    image: *backend
    restart: "no"
    env_file: *envfile
    command: ["celery", "worker", "--app=admetricks", "-l", "info", "-B"]
    volumes:
      - ./backend:/backend
    depends_on:
      - broker

  broker:
    image: rabbitmq:3
    env_file: *envfile
    ports:
      - 5672:5672
  
  nuxt:
    build:
      context: .
      dockerfile: Dockerfile_Frontend
    volumes:
      - ./frontend:/frontend
    ports:
      - "80:3000"
    depends_on:
      - rest_api
    command: bash -c "npm run dev"